spring:
  datasource:
    url: jdbc:h2:~/laintest
    username: lain
    password: lain
    driver-class-name: org.h2.Driver
  h2:
    console:
      settings:
        web-allow-others: true
      enabled: true
      path: /h2


lain:
  user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.97 Safari/537.36
  save-path:

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: false