spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:h2:@basedir@/db/laintest;mode=MYSQL;
    username: lain
    password: lain
    driver-class-name: org.h2.Driver
#    schema:
#      - classpath:initSql/init.sql
#      - classpath:initSql/tables_h2.sql
  h2:
    console:
      settings:
        web-allow-others: true
      enabled: true
      path: /h2

app:
  version: Ver_0.01

lain:
  user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.97 Safari/537.36
  save-path: D:/lain

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: false