server:
  port: 9000



lain:
  user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.97 Safari/537.36
  save-path: /root/cache/lain
logging:
  file:
    path: @basedir@/log
  level:
    root: error

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false

spring:
  h2:
    console:
      settings:
        web-allow-others: true
      enabled: true
      path: /h2